name: download

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          id: 50419836
          # name: build