name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  db:
    runs-on: self-hosted
    steps:
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "gitlab-runner"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: ls
      #working-directory: ${{github.workspace}}

