name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  db:
    runs-on: self-hosted
    steps:
      - if: ${{ hashFiles('gitlab-runner/*') }} != ''
        run: |
            pwd
            ls
      #working-directory: ${{github.workspace}}

