name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "gitlab-runner"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          docker pull complat/complat-ubuntu-runner:0.10.20
          docker cp $(docker run -it -d complat/complat-ubuntu-runner:0.10.20):/home/gitlab-runner .
      #working-directory: ${{github.workspace}}

