name: CI

on:
  workflow_dispatch:
  push:
# pull_request:
    branches: [ master ]

jobs:
  docker:
    container: 
      image: complat/complat-ubuntu-runner:0.10.20
    runs-on: self-hosted
    steps:
      - name: docker
       # uses: docker://complat/complat-ubuntu-runner:0.10.20
        run: |
            ls
        # working-directory: /github/home