name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: |
      ${{ true }}
    runs-on: self-hosted
    container: 
      image: complat/complat-ubuntu-runner:0.10.20
    steps:
      - run: |      
            pwd    
            ls -la
        working-directory: /github/  
      - run: |      
            pwd    
            ls -la
        working-directory: /github/workflow
      - run: |      
            pwd    
            ls -la
        working-directory: /github/home