name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: |
      ${{ true }}
    runs-on: self-hosted
    steps:
      - run: |
            which docker
            docker images
            ls -la $GITHUB_WORKSPACE
            la - la /home/ira/actions-runner/chemotion_saurus_github/_temp/_github_home
            
