name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: ${{ true }}
    runs-on: self-hosted
    steps:
      - name: docker native
        run: |
          docker images
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
