name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: ${{ true }}
    runs-on: self-hosted
    container: 
      image: complat/complat-ubuntu-runner:0.10.20
      volumes: 
        - /home/gitlab-runner:${{ github.workspace }}
    steps:
      - name: volume
        run: |
          ls
        working-directory: ${{ github.workspace }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
