name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: |
      ${{ false }} 
    container: 
      image: complat/complat-ubuntu-runner:0.10.20
    runs-on: self-hosted
    steps:
      - name: docker
       # uses: docker://complat/complat-ubuntu-runner:0.10.20
        run: |
            container_id=$(docker ps --all --format "{{.ID}}")
            docker exec -i $container_id bash
            ls
        working-directory: /github/home

  testbox:
    if: |
      ${{ true }} 
    runs-on: self-hosted
    container:
      image: azul/zulu-openjdk-alpine:8-jre
    steps:  
    - name: What java version do we have
      run: java -version
        