name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: |
      ${{ true }}
    runs-on: self-hosted
    container: 
      image: complat/complat-ubuntu-runner:0.10.20
    steps:
      - name: docker
        uses: docker://complat/complat-ubuntu-runner:0.10.20
      - run: |
            which docker
            docker images
            ls -la $GITHUB_WORKSPACE
            la - la /home/ira/actions-runner/chemotion_saurus_github/_temp/_github_home
            
