name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: ${{ true }}
    runs-on: self-hosted
    steps:
      - name: docker native
        run: |
          docker run -it -d complat/complat-ubuntu-runner:0.10.20
          docker exec -i $(docker ps --filter status=running | grep "complat/complat-ubuntu-runner:0.10.20" | awk '{ print $1 }') bash
          ls
