name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker_pull:
    if: hashFiles('gitlab-runner/Gemfile') == ''
    runs-on: self-hosted
    steps:
    - run: |
        docker pull complat/complat-ubuntu-runner:0.10.20
        docker cp $(docker run -it -d complat/complat-ubuntu-runner:0.10.20):/home/gitlab-runner .

  db:
    runs-on: self-hosted
    steps:
      - run: |
            pwd
            ls
      #working-directory: ${{github.workspace}}

