name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: |
      ${{ true }}
    runs-on: self-hosted
    steps:
    - name: docker
      uses: docker://complat/complat-ubuntu-runner:0.10.20
      with:
         args: docker images