name: self-hosted runner

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    if: ${{ true }}
    runs-on: self-hosted
    steps:
      - name: docker native
        run: |
          docker exec -i $(docker run -it -d complat/complat-ubuntu-runner:0.10.20) bash
          docker ps -a
      - run: |
            ls
